# deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: msag-website
  namespace: msag-website-namespace
spec:
  replicas: 10 
  selector:
    matchLabels:
      app: msag-website
  template:
    metadata:
      labels:
        app: msag-website
    spec:
      containers:
        - name: my-container
          image: yelfari/msag-website:latest 
          ports:
            - containerPort: 8080 
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
---
# service.yaml
apiVersion: v1
kind: Service
metadata:
  name: msag-website-service
  namespace: msag-website-namespace
spec:
  selector:
    app: msag-website
  ports:
    - protocol: TCP
      port: 80 # External port
      targetPort: 8080 # Container port
  type: LoadBalancer # Or ClusterIP if you're not using a cloud provider