name: Build and Push Docker Image

on:
  push:
    branches:
      - main  #Branch I want to push it into

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -t yelfari/msag-website:latest .

      - name: Push Docker image to Docker Hub
        run: |
          docker push yelfari/msag-website:latest